POST http://localhost:3000/api/phones HTTP/1.1
Content-Type: application/json

{
    "producer": "Hewlett",
    "model": "1212",
    "productedAt": "2021",
    "ram": "12",
    "screenSize": "14",
    "hasNfc": "true"
}

POST http://localhost:3000/api/phones HTTP/1.1
Content-Type: application/json

{
    "producer": "Apple",
    "productedAt": "2022",
    "ram": "12",
    "screenSize": "14",
    "hasNfc": "false"
}


POST http://localhost:3000/api/phones HTTP/1.1
Content-Type: application/json

{
    "producer": "Apple",
    "model": "MA-50",
    "productedAt": "ert",
    "ram": "12",
    "screenSize": "14",
    "hasNfc": "false"
}

POST http://localhost:3000/api/phones HTTP/1.1
Content-Type: application/json

{
    "producer": "Apple",
    "model": "MA-50",
    "productedAt": "     ",
    "ram": "12",
    "screenSize": "14",
    "hasNfc": "false"
}

POST http://localhost:3000/api/phones HTTP/1.1
Content-Type: application/json

{
    "producer": "Apple",
    "model": "MA-50",
    "productedAt": "206",
    "ram": "12",
    "screenSize": "14",
    "hasNfc": "false"
}

